Repository grafana/thema, pull requests merged in 2022-10, with the labels that each got.

#72 codegen: Introduce codegen CLI cmd and Go/TS gen packages
  assignable_test.go
  cmd/thema/lineage.go
  cmd/thema/lineage_subgen.go
  cmd/thema/main.go
  encoding/tgo/binding.tmpl
  encoding/tgo/doc.go
  encoding/tgo/gen.go
  go.mod
  go.sum
  schema_test.go
  surface.go
Labels: enhancement

#78 Quickstart guide for using Thema with Go
  docs/go-quickstart.md
Labels: documentation, enhancement

#80 cli: Make loaders work independent of disk state
  cmd/thema/data.go
  cmd/thema/lineage_bump.go
  cmd/thema/lineage_init.go
  cmd/thema/lineage_subgen.go
  cmd/thema/load.go
  cmd/thema/main.go
  encoding/tgo/gen.go
  load/load.go
Labels: bug
