Repository grafana/thema, pull requests merged in 2023-06, with the labels that each got.

#169 Lineage: Fix intermediate variable calc
  lineage.cue
  testdata/lineage/basic-multiversion.txtar
Labels: bug

#168 thema: Introduce basic benchmarks on Thema operations
  instance_test.go
  internal/txtartest/vanilla/bench.go
  internal/txtartest/vanilla/vanilla_txtar.go
  lineage_test.go
Labels: enhancement, performance

#173 thema: Remove native CUE sorting for drastic performance boost
  bind.go
  exemplars/exemplars_test.go
  lineage.cue
  lineage_test.go
  testdata/invalidlineage/empty-schemas.txtar
  testdata/invalidlineage/second-schema-versionless.txtar
  testdata/isappendonly/invalid/boundaries.txtar
  testdata/isappendonly/invalid/default.txtar
  testdata/isappendonly/invalid/embedref.txtar
  testdata/isappendonly/invalid/nested.txtar
  testdata/isappendonly/invalid/newfield.txtar
  testdata/isappendonly/invalid/noref.txtar
  testdata/isappendonly/invalid/optional.txtar
  testdata/isappendonly/invalid/refstruct.txtar
  testdata/isappendonly/invalid/stringconstraint.txtar
  testdata/lineage/basic-multiversion.txtar
  translate.cue
  traverse.cue
Labels: performance, prio/high, readiness/minimum

#176 thema: Tidy up base package and docs
  assignable.go
  encoding/cue/encode.go
  errors/errors.go
  impl.go
  instance.go
  lineage.go
  schema.go
  surface.go
Labels: documentation, enhancement
