Repository grafana/thema, pull requests merged in 2023-05, with the labels that each got.

#144 thema: Fix Translate() to same version
  instance_test.go
  testdata/internal/basic.cue
  testdata/lineage/basic-multiversion.txtar
  translate.cue
Labels: bug

#148 corpus: Add two known failure cases
  encoding/gocode/gocode_test.go
  lineage_test.go
  testdata/invalidlineage/addremove.txtar
  testdata/lineage/basic-multiversion.txtar
  testdata/lineage/unifyref.txtar
Labels: invariants

#153 thema: Add compat checking cases, improve errors
  bind.go
  lineage_test.go
  testdata/invalidlineage/compat/add-optional.txtar
  testdata/invalidlineage/compat/add-required.txtar
  testdata/invalidlineage/compat/change-default.txtar
  testdata/invalidlineage/compat/optional-to-required.txtar
  testdata/invalidlineage/compat/remove-optional.txtar
  testdata/invalidlineage/compat/remove-required.txtar
  testdata/invalidlineage/defonly.txtar
  testdata/invalidlineage/empty.txtar
  testdata/invalidlineage/schemaless.txtar
  testdata/lineage/basic-multiversion.txtar
  testdata/lineage/defaultchange.txtar
Labels: enhancement
